# Generated by Django 5.2.13 on 2026-04-11 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='property',
        ),
        migrations.DeleteModel(
            name='SupportTicket',
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.RenameField(
            model_name='property',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='price',
            new_name='rent',
        ),
        migrations.RemoveField(
            model_name='property',
            name='description',
        ),
        migrations.RemoveField(
            model_name='property',
            name='features',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image',
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied')], default='Available', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='property',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='core.tenant'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
