# Generated by Django 5.2.13 on 2026-04-11 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_payment_tenant_remove_order_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='features',
            field=models.TextField(blank=True, help_text='Comma-separated features'),
        ),
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('Rent', 'For Rent'), ('Sale', 'For Sale'), ('Both', 'Rent or Sale')], default='Rent', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sale price if for sale', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='rent',
            field=models.DecimalField(decimal_places=2, help_text='Monthly rent if for rent', max_digits=12),
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='core.property')),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
            },
        ),
    ]
