# Generated by Django 5.2.13 on 2026-04-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_property_description_property_features_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='property',
            name='listing_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rent',
        ),
        migrations.RemoveField(
            model_name='property',
            name='sale_price',
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Property sale price', max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold')], default='Available', max_length=20),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
