# Generated by Django 5.2.3 on 2026-04-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_property_tenant_remove_property_listing_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Negotiating', 'Negotiating'), ('Sold', 'Sold'), ('Closed', 'Closed')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='properties/'),
        ),
    ]
