# Generated by Django 5.2.3 on 2026-04-13 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_inquiry_status_alter_property_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(blank=True, help_text='Number of bathrooms (if applicable)', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(blank=True, help_text='Number of bedrooms (if applicable)', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Commercial', 'Commercial Center'), ('Plot', 'Plot / Land')], default='House', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='size_sqm',
            field=models.IntegerField(blank=True, help_text='Size in square meters', null=True),
        ),
    ]
